/* One-time 2026 Sto. Tomas Google Sheets import. */
(function(){
const books={sales:'1gwaR1C8po36NjQmpqB8Jxz8MIR74Q1iMBBGkv46c2sg',expenses:'13oz0xp1MJ3yeE_oVQIIebwtnwq2yOTIxzGFXQIbbG5Q'};
const sales=[['JAN.2026',982036458],['FEB.2026.',844681448],['MARCH.2026',1109601137],['APRIL 2026',18349253],['MAY2026',1893607177],['JUNE 2026',787108842],['JULY 2026',2121945413]],expenses=[['JAN.2026',5616370],['FEB.2026',1402824909],['MARCH.2026',1027089996],['APRIL 2026',1216502128],['MAY 2026',1800979607],['JUNE.2026',51078370],['JULY 2026',586600242]];
const t=v=>String(v??'').trim(),h=v=>t(v).toUpperCase().replace(/\s+/g,' '),n=v=>{const x=Number(String(v??'').replace(/[^0-9.-]/g,''));return Number.isFinite(x)?x:0},mo=v=>h(v).startsWith('JAN')?1:h(v).startsWith('FEB')?2:h(v).startsWith('MAR')?3:h(v).startsWith('APR')?4:h(v).startsWith('MAY')?5:h(v).startsWith('JUN')?6:7,dt=(v,m)=>{if(typeof v==='number'&&v>31)return new Date(Date.UTC(1899,11,30)+v*86400000).toISOString().slice(0,10);return '2026-'+String(m).padStart(2,'0')+'-'+String(Math.max(1,Math.min(31,Math.floor(n(v)||1)))).padStart(2,'0')};
async function get(book,gid){const r=await fetch('https://docs.google.com/spreadsheets/d/'+book+'/gviz/tq?tqx=out:json&gid='+gid);if(!r.ok)throw Error('Google Sheet could not be read ('+r.status+')');const x=await r.text(),m=x.match(/google\.visualization\.Query\.setResponse\((.*)\);?\s*$/s);if(!m)throw Error('Unexpected Google Sheet format');return(JSON.parse(m[1]).table.rows||[]).map(r=>(r.c||[]).map(c=>c?c.v:''))}
function pos(a,x){return a.findIndex(v=>v===x)}function mapSales(rows,tab,gid){const q=rows.findIndex(r=>r.some(v=>h(v)==='INVOICE NUMBER'));if(q<0)return[];const a=rows[q].map(h),i=x=>pos(a,x),sv=a.map((v,j)=>v.startsWith('SERVICE TYPE')?j:-1).filter(j=>j>=0),pay=a.findIndex(v=>v.includes('MODE OF PAYMENT'));return rows.slice(q+1).map((r,k)=>{const no=t(r[i('INVOICE NUMBER')]),ss=sv.map(j=>t(r[j])).filter(Boolean),amount=n(r[i('TOTAL AMOUNT')]);if(!no||(!ss.length&&!amount))return null;const paid=n(r[i('AMOUNT PAID')]);return{id:'STB-'+no+'-'+gid+'-'+(q+k+2),sourceInvoiceNo:no,sourceTab:tab,sourceRow:q+k+2,date:dt(r[i('DATE')],mo(tab)),customer:t(r[i('CLIENT NAME')])||'Walk-in client',contact:t(r[i('CONTACT NUMBER')]),address:t(r[i('ADDRESS')]),email:'',make:t(r[i('UNIT')]),model:t(r[i('YEAR MODEL')]),color:t(r[i('COLOR')]),plate:t(r[i('PLATE NUMBER')]),service:ss.join(' | ')||'Other services',panel:'',other:'',lines:ss.map((service,j)=>({service,detail:'',amount:j?0:amount})),parts:'',amount,amountPaid:paid,balance:Math.max(0,amount-paid),status:amount>0&&paid>=amount?'Paid':paid>0?'Partial':'Pending',source:'Imported Google Sheet',paymentMethod:t(r[pay])||'Not recorded',remarks:t(r[i('REMARKS')])}}).filter(Boolean)}
function mapExpenses(rows,tab,gid){const q=rows.findIndex(r=>r.some(v=>h(v)==='ITEM/SERVICE'));if(q<0)return[];const a=rows[q].map(h),i=x=>pos(a,x),pay=a.findIndex(v=>v.startsWith('MODE OF PAYMENT')),ref=a.findIndex(v=>v.includes('REF'));return rows.slice(q+1).map((r,k)=>{const description=t(r[i('ITEM/SERVICE')]),raw=t(r[i('TYPE OF EXPENSE')]),type=h(raw)==='TRANPORTATION ALLOWANCE'?'Transportation Allowance':raw,amount=n(r[i('TOTAL')])||n(r[i('AMOUNT')]);if(!description||!type||!amount)return null;return{id:'stb-exp-'+gid+'-'+(q+k+2),sourceTab:tab,sourceRow:q+k+2,date:dt(r[i('DATE')],mo(tab)),description,type,category:type,qty:Math.max(1,n(r[i('QTY')])||1),amount,mode:t(r[pay])||'Not recorded',reference:t(r[ref]),remarks:t(r[i('REMARKS')])}}).filter(Boolean)}
async function run(){const status=document.getElementById('cloudStatus');if(status)status.textContent='Importing Sto. Tomas records...';const inv=(await Promise.all(sales.map(([x,g])=>get(books.sales,g).then(r=>mapSales(r,x,g))))).flat(),exp=(await Promise.all(expenses.map(([x,g])=>get(books.expenses,g).then(r=>mapExpenses(r,x,g))))).flat();data.invoices=inv;data.expenses=exp;data.imports=data.imports||{};data.imports.stoTomasSheets2026={completedAt:new Date().toISOString(),invoices:inv.length,expenses:exp.length};save();render();setTimeout(save,700);if(status)status.textContent='Sto. Tomas imported — '+inv.length+' invoices and '+exp.length+' expenses'}
const wait=setInterval(()=>{const s=document.getElementById('cloudStatus'),b=document.querySelector('#branchControl .branch-name');if(!s||!b||b.textContent.trim()!=='15M Sto. Tomas'||!/Cloud synced/i.test(s.textContent))return;clearInterval(wait);if(data.imports&&data.imports.stoTomasSheets2026)return;run().catch(e=>{console.error(e);s.textContent='Sto. Tomas import needs attention'})},500);
}());
